name: flowcheck install dependencies & run code checkers
description: Install dependencies, run code checkers & run linter on creating and updating a Pull request.
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  enableTests:
    description: 'Enable or disable running tests'
    default: true

  enableLinter:
    description: 'Enable or disable running the linter'
    default: true

  testCommand:
    description: 'Command to run tests'
    default: 'composer run test'

  lintCommand:
    description: 'Command to run linter'
    default: 'npm run lint'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest
      shell: bash

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install npm dependencies
      run: npm ci
      shell: bash

    - name: Run tests
      run: |
        if [ ${{ inputs.enableTests }} == true ]; then
          ${GITHUB_WORKSPACE}/${{ inputs.testCommand }}
        else
          echo "Tests are disabled."
        fi
      shell: bash

    - name: Run linter
      run: |
        if [ ${{ inputs.enableLinter }} == true ]; then
          ${GITHUB_WORKSPACE}/${{ inputs.lintCommand }}
        else
          echo "Linter is disabled."
        fi
      shell: bash